add bboxes_from_yaml
HarvestX/YOLOX-ROS pull request #4
Opened 2022-03-14 07:27 UTC by Ar-Ray-code

2022-03-14 07:32 UTC, Ar-Ray-code commented
yamlから名前や色を読み込むプログラムを追加しました。
現時点では、手元に動かせるJetsonがないのでノートPCのOpenVINO版をベースにビルドしています。

2022-03-14 07:42 UTC, m12watanabe1a commented
いい感じです．

2022-03-15 14:00 UTC, Ar-Ray-code commented
yamlについて提案なのですが、クラスもリポジトリ内のyamlに追記する形にするとよりファイルをまとめられて使いやすくなりそうな気がします。

現時点でのコミットは、`class_yaml`でクラス情報のyamlのパスを別で指定できるようにしていますが、呼び出し元と同じファイルを参照しています。

↓以下、[639d3cd]https://github.com/HarvestX/YOLOX-ROS/pull/4/commits/639d3cd33587aca12a959e143889cfd63c6ed88d]の抜粋

https://github.com/HarvestX/YOLOX-ROS/blob/639d3cd33587aca12a959e143889cfd63c6ed88d/yolox_ros_cpp/yolox_ros_cpp/param/tiny_openvino.yaml#L1-L21

2022-03-16 01:12 UTC, m12watanabe1a commented
そっちの方が取り回しが楽そうですね．
Yaml内のkey(`class_info`)自体の深さなどに変化しなければお互い影響受けることはほぼないので問題ないです．
Keyの名前や深さを変更したい，という場合にご連絡いただければと思います．


検出情報を取り扱う側の方がいろいろと融通が利くので，検出側でよりよさそうなパラメータの定義とかがありそうであれば遠慮なくご提示ください．

2022-03-16 01:13 UTC, m12watanabe1a commented
まだコンパイル通せてないのですが，今晩ビルド環境用意してマージに向けていろいろと確認させていただければと思います 🙇‍♂️

2022-03-16 17:17 UTC, m12watanabe1a commented
ビルド通ってるの確認しました．

2022-03-17 02:28 UTC, m12watanabe1a commented
TensorRTの方でもビルド通ってること確認しました．
夕方に徳山にRealsense届くので，そこで動作確認いたします．

一方で，毎回カメラある環境で動作確認するのもしんどいと思うので，
決まった画像
https://github.com/Megvii-BaseDetection/YOLOX/blob/main/assets/dog.jpg
をPublishして帰ってくるレスポンスで適切にObjectがBounding Boxでかこまれているかを検証するテストコードなど書いておくと，サーバだけでコードの開発ができて，マージ可否の確認作業のイテレーションを楽に回せるのかなと思ったりします．

2022-03-17 02:39 UTC, Ar-Ray-code commented
[image_publisher](https://github.com/ros-perception/image_pipeline/tree/rolling/image_publisher)というaptで入手できるパッケージがあって、それを使うと便利かもしれません。
`image_publisher::ImagePublisher`をComponentで呼び出すことでRGBに点滅しながら右から左に流れるLenaの画像を取得できます。
```bash
sudo apt install ros-galactic-image-publisher
```

2022-03-17 03:44 UTC, m12watanabe1a commented
ありがとうございます！
確認してみます！

2022-03-17 06:39 UTC, Ar-Ray-code commented
yolox_ros_cpp_srvのリンクエラーらしきものが発生してしまったので、その修正のためにyolox_ros_cpp_srvの機能をyolox_ros_cppに埋め込んでデバッグしています。

2022-03-17 07:09 UTC, Ar-Ray-code commented
Serviceも一つのファイルに埋め込めたので、[yolox_ros_cpp_srv.cpp](https://github.com/HarvestX/YOLOX-ROS/blob/feature/galactic-name-dl/yolox_ros_cpp/yolox_ros_cpp/src/yolox_ros_cpp_srv.cpp)を消そうと思っていますがいかがでしょうか？
メンテナンス上も都合が良いと思います。

2022-03-17 07:20 UTC, m12watanabe1a commented
そうですね．そのほうが見通しがよいかもしれません．

よろしくお願いいたします．

2022-03-17 08:13 UTC, Ar-Ray-code commented
実行後にdog.jpgをダウンロードしてそれをsensor_msgs/Imageで送るようにしました。
```bash
ros2 launch yolox_ros_cpp yolox_service_dog.launch.py
> ファイルがない場合、"share/" ディレクトリにダウンロード
```

2022-03-17 08:39 UTC, Ar-Ray-code commented
なかなかいい感じだと思います。
デフォルトではリモートでもエラーにならないように、`imshow_is_show: False`になっているので画像を表示する場合は、`True`に変更します。

https://github.com/HarvestX/YOLOX-ROS/blob/854c58cb8ada4bbe1322cd7287593d3427d3611c/yolox_ros_cpp/yolox_ros_cpp/launch/yolox_service_dog.launch.py#L44

![Screenshot from 2022-03-17 17-32-43](https://user-images.githubusercontent.com/67567093/158770059-703e0378-703e-49dc-a6ec-3c3fe1688b49.png)

2022-03-17 09:32 UTC, m12watanabe1a commented
動きましたわ 🎉 
これで，同じ画像に対して検出を書けると大体いつも
- だいたいN個のBBoxが見つかり，それぞれ[dog, car, bicycle]であり，BBoxの頂点は[p1, p2, p3, p4]の領域内部に存在する．
っていうテストがかけて，このスクリプトがきちんと回ること，っていうのをマージの可否の判断点とすると，ガシガシ変更加えても検証の痛みが少なくて済むと思います．

加えて，
- 'class_info'の中の['dog', 'car', 'bicycle']の文字の部分に['hoge', 'huga', 'piyo']を差し込むと，class_idも応じて変化すること．
- 'class_info'の中の色情報を別の色にするとBoundingBoxの色が応じて変化すること，などを検証してマージしましょう．

2022-03-17 09:37 UTC, m12watanabe1a commented
実行パスが`~/ros2_ws`に依存する箇所が何点かあったのでよろしければそのうちパッチ投げさせてください．

2022-03-22 04:33 UTC, Ar-Ray-code commented
入れ替えできました。
dogがcatの位置になっているのが気になったので、見てみます。
![Screenshot from 2022-03-22 13-27-51](https://user-images.githubusercontent.com/67567093/159408271-6af3ca17-685f-40d8-ad88-c60cc0e339bb.png)

2022-03-22 04:36 UTC, Ar-Ray-code commented
色が入れ替わっていませんでした…
![Screenshot from 2022-03-22 13-34-36](https://user-images.githubusercontent.com/67567093/159408964-54df4d33-074b-470a-9e2a-c817fd4b1dcd.png)

2022-03-23 09:09 UTC, m12watanabe1a commented
catとDog，indexが一個ずれとりますね．．．
ちょっと確認します．．．

2022-03-23 09:16 UTC, m12watanabe1a commented
Modelのせいっぽいwww
![image](https://user-images.githubusercontent.com/40206149/159664691-b8803737-0e7b-4ab5-b433-06dec995d954.png)
![image](https://user-images.githubusercontent.com/40206149/159664836-f4c79059-abf9-4fb4-abdd-d9f7874e5f99.png)

2022-03-23 09:17 UTC, m12watanabe1a commented
あの犬，猫に見えちゃうんすね....w

実装のミスとかではなさそうです

いずれにせよ，デフォのパラメータであの挙動しちゃうならテストケースとしては不適ですかね．．．笑

2022-03-23 09:22 UTC, m12watanabe1a commented
色の変更の方も問題ないですね．

![image](https://user-images.githubusercontent.com/40206149/159665827-6b5b6e01-2b6b-46a1-ad83-54e632c7efb1.png)

2022-03-23 09:22 UTC, m12watanabe1a commented
```
diff --git a/yolox_ros_cpp/yolox_ros_cpp/param/tiny_openvino.yaml b/yolox_ros_cpp/yolox_ros_cpp/param/tiny_openvino.yaml
index b9b6b8a..611e2ee 100644
--- a/yolox_ros_cpp/yolox_ros_cpp/param/tiny_openvino.yaml
+++ b/yolox_ros_cpp/yolox_ros_cpp/param/tiny_openvino.yaml
@@ -12,8 +12,8 @@ publish_boundingbox_topic_name: yolox/bounding_boxes
 class_yaml: yolox_ros_cpp/param/tiny_openvino.yaml # reopen yaml to load class_info
 class_info: # class_name: bounding_box_color [R, G, B]
   person: [0.000, 0.447, 0.741]
-  bicycle: [0.850, 0.325, 0.098]
-  car: [0.929, 0.694, 0.125]
+  bicycle: [0.000, 1.000, 0.000]
+  car: [0.000, 0.000, 1.000]
   motorcycle: [0.494, 0.184, 0.556]
   airplane: [0.466, 0.674, 0.188]
   bus: [0.301, 0.745, 0.933]
@@ -26,7 +26,7 @@ class_info: # class_name: bounding_box_color [R, G, B]
   parking meter: [0.000, 1.000, 0.000]
   bench: [0.000, 0.000, 1.000]
   bird: [0.667, 0.000, 1.000]
-  cat: [0.333, 0.333, 0.000]
+  cat: [1.000, 0.000, 0.000]
   dog: [0.333, 0.667, 0.000]
   horse: [0.333, 1.000, 0.000]
   sheep: [0.667, 0.333, 0.000]
```

2022-03-23 09:29 UTC, m12watanabe1a approved these changes

2022-03-23 09:29 UTC, m12watanabe1a commented on yolox_ros_cpp/yolox_ros_cpp/include/yolox_ros_cpp/bboxes_from_yaml.hpp
> +} coco;
僕も完全に準拠できてないですが，可能であれば型名は大文字で統一していただければと思います
https://ttsuki.github.io/styleguide/cppguide.ja.html#Type_Names

2022-03-23 09:29 UTC, m12watanabe1a commented on yolox_ros_cpp/yolox_ros_cpp/include/yolox_ros_cpp/bboxes_from_yaml.hpp
> +            color bbox_color;
型変換三回やるより，こういう感じでまとめた方が処理系がすっきりするかと思います！
```c++
            // get color
            auto color_array = it->second.as<std::array<float, 3>>();
            color bbox_color;
            bbox_color.r = color_array.at(0);
            bbox_color.g = color_array.at(1);
            bbox_color.b = color_array.at(2);

            coco data;
            data.name = it->first.as<std::string>();
            data.rgb = bbox_color
```

2022-03-23 09:29 UTC, m12watanabe1a commented on yolox_ros_cpp/yolox_ros_cpp/package.xml
>    <depend>sensor_msgs</depend>
ここのexec_dependに教えていただいたこのパッケージを追記していただきたいです．

https://github.com/HarvestX/YOLOX-ROS/pull/4#issuecomment-1069944876

2022-03-23 09:29 UTC, m12watanabe1a commented on yolox_ros_cpp/yolox_ros_cpp/param/tiny_openvino.yaml
> +class_yaml: yolox_ros_cpp/param/tiny_openvino.yaml # reopen yaml to load class_info
これも削れると更にスッキリしそうですが，探してみた感じ方法はなさそうですね．．．仕方ない．．．

2022-03-23 09:35 UTC, m12watanabe1a commented
挙動的には受け入れ基準を満たしているのでApproveとさせていただきました．
特に直さなくてもいいかなと思ったところはResolveとさせていただいたので，上記のレビュー巻き取っていただければと思っております．

よろしくお願いいたします

2022-03-23 09:35 UTC, m12watanabe1a approved these changes

2022-03-23 09:37 UTC, m12watanabe1a requested changes
よろしくお願いいたします．

2022-03-23 23:37 UTC, Ar-Ray-code reviewed
:+1:

2022-03-24 01:08 UTC, m12watanabe1a approved these changes

2022-03-24 01:26 UTC, Ar-Ray-code commented
マージしてもいいですか？

2022-03-24 01:46 UTC, m12watanabe1a commented
@Ar-Ray-code OKです．
お願いいたします．

2022-03-24 01:48 UTC, merged

2022-03-24 01:52 UTC, m12watanabe1a commented
:beers: